name: my-environment
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pytorch=2.3.0
  - torchaudio=2.3.0
  - torchvision=0.18.0
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - matplotlib=3.7.2
  - seaborn=0.13.2
  - tqdm=4.66.4
  - requests=2.31.0
  - pip
  - pip:
    - black==24.4.2
    - fsspec==2024.5.0
    - filelock==3.13.1
    - jinja2==3.1.3
    - pytorch-lightning==2.4.0
    - yaml==0.2.5
